version: '3.3'
services:
   db:
     image: mysql:8.0.28
     volumes:
       - C:\Users\a844918\Desktop\DockerExample\mysql-vol:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: user2022
       #MYSQL_USER: root -> de todos modos se conecta a root
       MYSQL_PASSWORD: user2022
     ports:
       - "3307:3306"
     restart: always
     container_name: mysql
